inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
  - "*.gemspec"
  RunRailsCops: true

Metrics/LineLength:
  Enabled: false

# Offense count: 61
Metrics/AbcSize:
  Max: 59