#!/usr/bin/env ruby

require 'tika_wrapper'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: tika_wrapper [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on("--version VERSION", "Specify a tika version to download (default: #{TikaWrapper.default_tika_version})") do |v|
    options[:version] = v
  end

  opts.on("-pPORT", "--port PORT", "Specify the port tika should run at (default: 9998)") do |p|
    options[:port] = p
  end
end.parse!

# default to verbose
options[:verbose] = true if options[:verbose].nil?

TikaWrapper.wrap(options) do |conn|
  while conn.status
    sleep 1
  end
end
